### ISSUE TITLE
Specifying "user" and "address" during node creation vs activation

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#129]
During the review of #102, @ketiltrout pointed out that originally the username and address were only meaningful when the node was mounted (activated in current parlance), meaning you would create the node without address or username and then specify each time them when calling "mount" or "mount_transport".

Given that, perhaps specifying "address" and "user" should only be possible in `node activate`, and not at all with `node create`.

(Depending on the outcome of this discussion, we should also check that `node modify` behaves right as well.)

**Comment by ketiltrout** [comment]
I think allowing the specification of user and address at node creation time is a good idea.

With the exception of transport disks, most nodes are permanently mounted someplace, so having those parameters set when the node is first set up makes sense.  Then you can call `node activate` without having to re-enter those parameters each time.

I think I would:
- allow optionally specifying `user` and `address` at node creation time which will set the values int the table
- allow calling `node activate` without those parameters (which I think is already possible).  If `user` and `address` are set in the table already, no change is made to those values when the node is activated
- if `node activate` is called with the parameters, the table is updated when the node is activated (this is the transport disk mode)
- have a way in `node deactivate` to specify whether or not those values should be cleared when the node is deactivated (again, because it wouldn't make sense for transport disks to retain those values).  I don't have a strong opinion on which would be the default mode
- maybe have some method of clearing those values during `node activate`, perhaps via a "null" value, though this could be done through the above `node deactivate`

Note that not having a `user` or `address` specified for an activated node is a valid thing to do if you want to prevent remote `alpenhornd`s from trying to copy data out of them.

And there should be a way when mounting transport disks to ensure they aren't mounted with an incorrect user/address since these change all the time (hence my value-clearing mode proposal for `node deactivate` ).  Currently `alpenhorn_chime` script (in `alpenhorn_tools`) provides this protection by taking on the burden of figuring out what values to set these to for transport disks.

**Comment by ketiltrout** [comment]
Implemented in #221.  address and username can be set at both node creation time and activation time, as well as at any other time via "modify".
