### ISSUE TITLE
Consider interaction of imported files cache and special import cases

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#2]
If the cache is based on ArchiveFile contents, we still need to register copies of the file on the collection server, if:

1. it does not exist, or 
2. it does exist but has been labelled as corrupt. 

If (2), check again.

**Comment by jrs65** [comment]
Sounds good. We should definitely make sure we generate the cache based on the files known to be on the actual node. I think the entry on the wiki page has the query about correct ([here](../wiki/Alpenhorn-Redesign#import-list)).

Also we probably only want to check against the import list at the initial pass over the node when alpenhorn starts. This is good on another front because it means we don't need to update the cache at all (or even keep it around after we've done that pass over the data).

It might actually be interesting to see if there's any performance hit to stat-ing the files to get their size. That way we could quickly check the file size against the db on startup too.

**Comment by jrs65** [comment]
We think this is resolved.f
