### ISSUE TITLE
Reimporting files with a corrupted ArchiveFileCopy does not mark it clean

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#3]
See test case `test_import_corrupted` in test_imports.py.

**Comment by jrs65** [comment]
I think the desired behaviour is that the file gets marked with `has_file='M'`. That way it gets explicitly checked in the next iteration of alpenhorns's main loop, an then if successful gets set to `has_file='Y'`. I also think it should set `wants_file='Y'` regardless of what is currently set, otherwise why did you import the file?

**Comment by jrs65** [comment]
So that would mean that the check in test_import.py#L220 should be for `{'has_file': 'M', 'wants_file': 'Y'}`

**Comment by cubranic** [comment]
Sounds good!
