### ISSUE TITLE
Rename mount to something else

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#43]
`alpenhorn mount` prints at the end "Successfully mounted _node_". This is not entirely accurate, as the daemon doesn't have to be running on the node's host at the time, and indeed there are no guarantees that the node's filesystem is mounted at the OS level. Perhaps something like "_node_ is now available on host _host_", or "marked for mounting"?

**Comment by jrs65** [comment]
Yeah. The fact it's called mount in the database is a little confusing. I agree that modifying the message for clarity would be good. Even just making it clear that the node is mounted only in alpenhorns database.

**Comment by ketiltrout** [comment]
I propose renaming the `mount`/`unmount` commands to `activate`/`deactivate` and the verbiage to "Successfully activated/deactivated _node_".  The `mount_transport`/`unmount_transport` commands can stay as-is, since they do actually try to mount/unmount the specified node.

Do we also want to rename the `mounted` column to, say, `active`?

**Comment by jrs65** [comment]
That sounds pretty good to me (both the renamed commands and column), though I might be tempted to still rename the `_transport` versions.

**Comment by cubranic** [comment]
If we rename "mount_transport" to "activate_transport", the fact that it also mounts the disk is not immediately obvious. (Conversely, I guess if we don't, it's similarly not obvious that the second step is done.)

**Comment by ketiltrout** [comment]
How about renaming them to `mount_and_activate`/`deactivate_and_unmount`, since you can use the commands on other storage nodes that aren't actually transport disks.

I also propose keeping the old commands, but instead of them being simple aliases, have them spit out a deprecation warning then carry on doing what they're supposed to do, to encourage users to switch to the new ones.

**Comment by cubranic** [comment]
In the two commits above, I implemented the renaming of the 'mount/unmount/mounted' commands and the StorageNode.mounted database column. I did not change the naming of the "*_transport" commands, since they do mount the filesystem too and the "mount_and_activate" seemed way too long for a command name.

I'll wait for your comments before submitting the PR.

**Comment by cubranic** [comment]
PR submitted: #95. I have both of @ketiltrout and @jrs65 as reviewers, please comment on my rename choice. (In particular, I kept "mount_transport".)
