### ISSUE TITLE
Missing constraint on ArchiveFileCopy

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#59]
There should be a unique key constraint added to `ArchiveFileCopy` along the lines of 
```
pw.CompositeKey('file','node')
```
to enforce only one copy of a file per node.

**Comment by jrs65** [comment]
Agreed. I’m surprised we don’t have that one.

R


On 21 November 2018 at 15:30:57, ketiltrout (notifications@github.com)
wrote:

There should be a unique key constraint added to ArchiveFileCopy along the
lines of

pw.CompositeKey('file','node')

to enforce only one copy of a file per node.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/radiocosmology/alpenhorn/issues/59>, or mute the thread

**Comment by cubranic** [comment]
So I'm not sure why adding:
```py
class ArchiveFileCopy(base_model):
    # ...
    class Meta:
        indexes = (
            (('file', 'node'), True),
        )
        primary_key = pw.CompositeKey('file', 'node')
```
works, but using `primary_key` does not:
```py
class ArchiveFileCopy(base_model):
    # ...
    class Meta:
        primary_key = pw.CompositeKey('file', 'node')
```
There are no errors, it's just that the ArchiveFileCopy instances aren't being saved into the table.
