### ISSUE TITLE
alpenhornd ignores new mounted nodes if mounted node count drops to zero

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#60]
We've seen on `jingle` the following behaviour:
* `alpenhornd` working fine with transport disks mounted
* All transport disks are unmounted, leaving `jingle` with no mounted storage nodes
* New transport disks are added to jingle and mounted using `mount_transport`
* Although the new nodes are now properly mounted on `jingle` in the database, `alpenhornd` ignores them, and continues to operate as if there are no nodes mounted.

An `alpenhornd` restart is required to get out of this state.

**Comment by cubranic** [comment]
@ketiltrout This shouldn't happen in Alpenhorn2. The service runs in `update.update_loop` ([src](https://github.com/radiocosmology/alpenhorn/blob/master/alpenhorn/update.py#L38)) with a check for local storage nodes in every pass:
```py
    while True:
        loop_start = time.time()
        for node in st.StorageNode.select().where(st.StorageNode.host == host):
            update_node(node)
        loop_time = time.time() - loop_start
        remaining = config.config['service']['update_interval'] - loop_time
        if remaining > 1:
            time.sleep(remaining)
```

**Comment by ketiltrout** [comment]
That's the exact same loop we have in alpenhorn1 where we see the problem.  I really don't understand what's going on.

**Comment by cubranic** [comment]
Assuming the error is in our code, it's possible the filter `where(st.StorageNode.host == host)` fails because new transport disks got mounted with a NULL in the `host` field or using a hostname different from the one used in alpenhornd (maybe FQDN vs short name?).

Or do you mean that you checked the DB and everything absolutely looks like it should have been selected for the update loop?
